### ISSUE TITLE
可以不用显示版本号么？

### ISSUE THREAD

**Issue by whatlin** [guMcrey/version-rocket#11]
![image](https://user-images.githubusercontent.com/67350580/196131923-2599e914-4e91-4043-b988-c93835d9c59c.png)

**Comment by guMcrey** [comment]
你好, 可以的. 方法如下:

1. 在全局 css 文件中添加如下 css 样式

```css
<style>
#version-rocket .version-subtitle {
  display: none;
}
</style>
```

2. 如果使用了 vue 的单文件组件, 也可直接在单文件组件中添加以下代码，css 预处理器以 less 为例（如果本地使用了 scss 或 stylus，记得替换一下 lang 属性值）
    ⚠️: 不要加 scoped 属性

```vue
<style lang="less">
#version-rocket .version-subtitle {
  display: none;
}
</style>
```

希望对你有帮助, 感谢关注💗
